Models/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SemanticWeb.Models
{
    public class Post
    {
        public Post()
        {
            DatePosted = DateTime.Now;
        }
        public int Id { get; set; }
        [Display(Name = "Tiêu đề")]
        public string Title { get; set; }
        [Display(Name = "Nội dung")]
        public string Content { get; set; }
        [Display(Name = "Hình ảnh")]
        public string ImageURL { get; set; }
        [DataType(DataType.Date)]
        [Display(Name = "Ngày đăng")]
        public DateTime DatePosted { get; set; }
        public string UserID { get; set; }
        [Display(Name = "Khu vực")]
        public int AreaId { get; set; }
        public Area Area { get; set; }
        public ICollection<Comment> Comments { get; set; }
    }
}

ViewModels/PostViewModel.cs
using Microsoft.AspNetCore.Http;
using SemanticWeb.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SemanticWeb.ViewModels
{
    public class PostViewModel
    {
        public PostViewModel()
        {
            DatePosted = DateTime.Now;
        }
        public string Title { get; set; }
        public string Content { get; set; }
        public IFormFile ImageURL { get; set; }
        [DataType(DataType.Date)]
        public DateTime DatePosted { get; set; }
        public string UserID { get; set; }
        public int AreaId { get; set; }
        public Area Area { get; set; }
        public ICollection<Comment> Comments { get; set; }
    }

}

Controllers/PostsController.cs
using System;
using System.IO;
using System.Net;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http.Features;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SemanticWeb.Data;
using SemanticWeb.Models;
using SemanticWeb.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using VDS.RDF.Query;
using VDS.RDF.Parsing;
using VDS.RDF;

namespace SemanticWeb.Controllers
{
    public class PostsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<CustomUser> _userManager;

        private readonly IWebHostEnvironment _webHostEnvironment;
        public PostsController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment, UserManager<CustomUser> userManager)
        {
            _webHostEnvironment = webHostEnvironment;
            _context = context;
            _userManager = userManager;
        }

        // GET: Posts
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Posts.ToListAsync());
        }

        // GET: Posts/FindByArea
        public ActionResult Theme()
        {
            return View();
        }

        // GET: Posts/PostsByArea/haichau
        public async Task<IActionResult> PostsByTheme(string theme)
        {
            var postsByTheme = new List<Post>();

            SparqlParameterizedString queryString = new SparqlParameterizedString();
            queryString.Namespaces.AddNamespace("has", new Uri("https://localhost:44331/Posts/"));
            string subject = "<https://localhost:44331/Posts/PostsByTheme?theme=" + theme + ">";
            queryString.CommandText = "SELECT ?post where {" + subject + " has:Details ?post} ";


            SparqlQueryParser parser = new SparqlQueryParser();
            SparqlQuery query = parser.ParseFromString(queryString);

            IGraph g = new Graph();
            FileLoader.Load(g, "D:\\ThucHanh\\Web\\123Travel\\123-Travel\\Data\\danang.rdf");

            Object results = g.ExecuteQuery(query);
            if (results is SparqlResultSet)
            {
                SparqlResultSet rset = (SparqlResultSet)results;
                foreach (SparqlResult r in rset)
                {
                    var postTitle = r.ElementAt(0).Value.ToString();
                    var post = await _context.Posts.Where(p => p.Title == postTitle).FirstOrDefaultAsync();
                    postsByTheme.Add(post);
                }
            }

            return View(postsByTheme);
        }

        // GET: Posts/PostsByArea/haichau
        public async Task<IActionResult> SearchPosts(IFormCollection collection)
        {
            var searchString = collection["searchStringRDF"][0].ToString();
            var searchWords = searchString.Split(" ");
            var list = new List<Post>();

            SparqlParameterizedString queryString = new SparqlParameterizedString();
            queryString.Namespaces.AddNamespace("nr", new Uri("https://localhost:44331/"));
            if (searchWords.Contains("biển") || searchWords.Contains("núi"))
            {
                string keyword = searchWords.Where(w => w == "biển" || w == "núi").FirstOrDefault();
                queryString.CommandText = "SELECT ?area where {?area nr:Near '" + keyword + "'@vn}";
            }
            else if (searchWords.Contains("beach") || searchWords.Contains("mountain"))
            {
                string keyword = searchWords.Where(w => w == "beach" || w == "mountain").FirstOrDefault();
                queryString.CommandText = "SELECT ?area where {?area nr:Near '" + keyword + "'@en}";
            }
            else if (searchString == "")
            {
                queryString.Namespaces.AddNamespace("has", new Uri("https://localhost:44331/Posts/"));
                queryString.CommandText = "SELECT ?post where {?theme has:Details ?post} ";
            }

            SparqlQueryParser parser = new SparqlQueryParser();
            SparqlQuery query = parser.ParseFromString(queryString);
            IGraph g = new Graph();
            FileLoader.Load(g, "D:\\ThucHanh\\Web\\123Travel\\123-Travel\\Data\\danang.rdf");

            Object results = g.ExecuteQuery(query);
            if (results is SparqlResultSet)
            {

                SparqlResultSet rset = (SparqlResultSet)results;
                foreach (SparqlResult r in rset)
                {
                    if (searchString == "")
                    {
                        var postTitle = r.ElementAt(0).Value.ToString();
                        var post = await _context.Posts.Where(p => p.Title == postTitle).FirstOrDefaultAsync();
                        list.Add(post);
                    }
                    else
                    {
                        int lastSlash = r.ToString().LastIndexOf('/');
                        string area = r.ToString().Substring(lastSlash + 1).ToLower();
                        var posts = await _context.Posts.Where(p => p.Area.Name == area).ToListAsync();
                        list.AddRange(posts);
                    }
                }
            }

            return PartialView("~/Views/Home/NewsFeedPartial.cshtml", list);
        }

        // GET: Posts/History
        public ActionResult ViewHistory()
        {
            var currentUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var postsOfCurrentUser = _context.Posts.Where(post => post.UserID == currentUserId);
            return View(postsOfCurrentUser.ToList());
        }

        // GET: Posts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts.FirstOrDefaultAsync(m => m.Id == id);
            var comments = await _context.Comments.Where(comment => comment.PostId == id).ToListAsync();

            CommentViewModel commentViewModel = new CommentViewModel()
            {
                Post = post,
                Comments = comments

            };

            return View(commentViewModel);
        }

        // GET: Posts/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Posts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Title,Content,AreaId,ImageURL")] PostViewModel vm)
        {
            var currentUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            vm.UserID = currentUserId;
            var area = _context.Areas.Where(a => a.AreaId == vm.AreaId).FirstOrDefault();
            string stringFileName = UploadFile(vm);
            var post = new Post()
            {
                Title = vm.Title,
                Content = vm.Content,
                DatePosted = vm.DatePosted,
                UserID = vm.UserID,
                AreaId = vm.AreaId,
                Area = area,
                ImageURL = stringFileName
            };
            if (ModelState.IsValid)
            {
                await _context.AddAsync(post);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(ViewHistory));
            }
            return View(vm);
        }

        private string UploadFile(PostViewModel vm)
        {
            string fileName = null;
            if (vm.ImageURL != null)
            {
                string uploadDir = Path.Combine(_webHostEnvironment.WebRootPath, "images");
                fileName = Guid.NewGuid().ToString() + "-" + vm.ImageURL.FileName;
                string filePath = Path.Combine(uploadDir, fileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    vm.ImageURL.CopyTo(fileStream);
                }
            }
            return fileName;
        }

        // GET: Posts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var post = await _context.Posts.FindAsync(id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Content,AreaId,ImageURL")] Post post)
        {
            if (id != post.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var currentUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                    post.UserID = currentUserId;
                    _context.Update(post);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PostExists(post.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SemanticWeb.Data;
using SemanticWeb.ViewModels;

namespace SemanticWeb.Controllers
{
    public class UsersController : Controller
    {
        private readonly UserManager<CustomUser> _userManager;
        private readonly ApplicationDbContext _context;

        public UsersController(ApplicationDbContext context, UserManager<CustomUser> userManager)
        {
            _userManager = userManager;
            _context = context;
        }

        // GET: Users
        [Authorize(Roles = "Administrator")]
        public async Task<ActionResult> Index(string searchString, string sortOrder)
        {
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";
            ViewData["CurrentFilter"] = searchString;

            //var users = await _userManager.Users.ToListAsync();
            var users = from user in _userManager.Users select user;
            if (!String.IsNullOrEmpty(searchString))
            {
                users = users.Where(user => user.UserName.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    users = users.OrderByDescending(user => user.Name);
                    break;
                case "Date":
                    users = users.OrderBy(users => users.DateJoined);
                    break;
                case "date_desc":
                    users = users.OrderByDescending(users => users.DateJoined);
                    break;
                default:
                    users = users.OrderBy(user => user.Name);
                    break;
            }
            return View(await users.AsNoTracking().ToListAsync());
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(string id)
        {
            var currentUser = await _userManager.FindByIdAsync(id);
            var posts = await _context.Posts.Where(p => p.UserID == id).ToListAsync();
            UserViewModel userViewModel = new UserViewModel()
            {
                Username = currentUser.UserName,
                Phone = currentUser.PhoneNumber,
                Name = currentUser.Name,
                DateJoined = currentUser.DateJoined,
                Posts = posts
            };
            return View(userViewModel);
        }

        // GET: Users/Lock/5
        public async Task<ActionResult> LockUser(string id)
        {
            var userToLock = await _userManager.Users.FirstOrDefaultAsync(m => m.Id == id);
            await _userManager.SetLockoutEnabledAsync(userToLock, true);
            await _userManager.SetLockoutEndDateAsync(userToLock, DateTime.Today.AddYears(100));
            return View("Index", _userManager.Users.ToList());
        }
        public async Task<ActionResult> UnlockUser(string id)
        {
            var userToLock = await _userManager.Users.FirstOrDefaultAsync(m => m.Id == id);
            await _userManager.SetLockoutEnabledAsync(userToLock, false);
            await _userManager.SetLockoutEndDateAsync(userToLock, DateTime.Now);
            return View("Index", _userManager.Users.ToList());
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userToDelete = await _userManager.Users.FirstOrDefaultAsync(m => m.Id == id);
            if (userToDelete == null)
            {
                return NotFound();
            }

            return View(userToDelete);
        }

        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var userToDelete = await _userManager.FindByIdAsync(id);
            await _userManager.DeleteAsync(userToDelete);
            return RedirectToAction("Index");
        }

    }
}

Views/Posts/CommentPartial.cshtml
@model SemanticWeb.ViewModels.CommentViewModel
<div id="all-comments">
    @foreach (var comment in Model.Comments.Reverse())
    {

        <div class="row">
            @*<h6 class="mx-5">@comment.Username</h6>
                <p class="ml-5">@comment.DateComment</p>*@
            <h6 class="ml-3 mr-2 text-primary">@comment.Username</h6>
            <p>@comment.Content</p>
        </div>


        @*<div class="mb-5">@comment.Content</div>*@
        <div><small>@comment.DateCommented</small></div>
        <hr />
    }
</div>

Views/Posts/Create.cshtml
@model SemanticWeb.ViewModels.PostViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row mx-5 my-5">
    <div class="col-5">
        <h1 style="font-family: 'Pangolin', cursive;">Tạo bài đăng mới</h1>
        <form asp-action="Create" enctype="multipart/form-data" method="post" id="create-form">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label">Tiêu đề</label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label">Mô tả</label>
                <textarea asp-for="Content" class="form-control" rows="5"></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AreaId" class="control-label">Khu vực:</label>
                <select asp-for="AreaId" class="form-control">
                    <option value=1>Hải Châu</option>
                    <option value=2>Thanh Khê</option>
                    <option value=3>Sơn Trà</option>
                    <option value=4>Liên Chiểu</option>
                    <option value=5>Cẩm Lệ</option>
                    <option value=6>Hòa Vang</option>
                    <option value=7>Ngũ Hành Sơn</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="ImageURL" class="control-label">Link ảnh</label>
                <br />
                <input asp-for="ImageURL" class="" type="file" />
                <span asp-validation-for="ImageURL" class="text-danger"></span>
            </div>
            <div class="form-group float-right">
                <input type="submit" value="Tạo mới" class="btn btn-success btn-lg" />
            </div>
        </form>

    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Posts/Delete.cshtml
@model SemanticWeb.Models.Post

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Post</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Content)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DatePosted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DatePosted)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Area)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Area.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Posts/Details.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<SemanticWeb.Data.CustomUser> UserManager
@inject SignInManager<SemanticWeb.Data.CustomUser> SignInManager
@model SemanticWeb.ViewModels.CommentViewModel
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}





<div class="row mt-5 mx-5">
    <div class="col-6 shadow col-6 shadow d-flex justify-content-center align-items-center">
        <img src="~/Images/@Model.Post.ImageURL" alt="Picture" class="img-fluid" />
    </div>
    <div class="col-6 mt-2 px-5">
        <h2 style="font-family: 'Pangolin', cursive;">@Model.Post.Title</h2>
        <p>
            @Model.Post.Content
        </p>
        <div class="row">
            <div class="col-6">
                <h6>
                    Ngày đăng:
                    <span class="font-weight-normal"> @Model.Post.DatePosted.ToString("dd/MM/yyyy")</span>
                </h6>
                <h6>
                    Địa điểm:
                    @switch (Model.Post.AreaId)
                    {
                        case 1:
                            <span class="font-weight-normal">
                                Hải Châu
                            </span>
                            break;
                        case 2:
                            <span class="font-weight-normal">
                                Thanh Khê
                            </span>
                            break;
                        case 3:
                            <span class="font-weight-normal">
                                Sơn Trà
                            </span>
                            break;
                        case 4:
                            <span class="font-weight-normal">
                                Liên Chiểu
                            </span>
                            break;
                        case 5:
                            <span class="font-weight-normal">
                                Cẩm Lệ
                            </span>
                            break;
                        case 6:
                            <span class="font-weight-normal">
                                Hòa Vang
                            </span>
                            break;
                        default:
                            <span class="font-weight-normal">
                                Ngũ Hành Sơn
                            </span>
                            break;
                    }
                </h6>
                <h6>
                    Người đăng:
                    <span class="font-weight-normal">
                        <a asp-action="Details" asp-route-id="@Model.Post.UserID" asp-controller="Users">
                            @UserManager.FindByIdAsync(Model.Post.UserID).Result.UserName
                        </a>
                    </span>

                </h6>
            </div>
        </div>
    </div>
</div>



@if (SignInManager.IsSignedIn(User))
{
    <div class="row mt-5 mx-5">
        <div class="col-6">
            <h4>Bình luận</h4>
            <form method="post" action="/Posts/AddComment" id="form-comment">
                <textarea @*class="form-element"*@ name="comment" cols="80" rows="3" id="textarea-comment"> </textarea>
                <br />
                <input @*class="form-element"*@ value=@User.Identity.Name name="userId" type="hidden" />
                <input type="hidden" value=@Model.Post.Id name="postId" />
                <button type="submit" class="btn btn-info float-right w-25">Đăng</button>
            </form>
        </div>
    </div>
}
else
{
    <div class="row mt-5 mx-5">
        <div class="col-6">
            <h4>Bình luận</h4>
            <h6 class="font-italic font-weight-normal">(Bạn cần <span><a asp-area="Identity" asp-page="/Account/Login">đăng nhập</a></span> để đăng bình luận)</h6>
        </div>
    </div>
}

<div class="mt-5 col-6 mx-5" id="comments-box">
    <partial name="CommentPartial" />
</div>

Views/Posts/Edit.cshtml
@model SemanticWeb.Models.Post

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row mx-5 my-5">
    <div class="col-5">
        <h1 style="font-family: 'Pangolin', cursive;">Chỉnh sửa bài đăng</h1>
        <hr />
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Id" />
                    <div class="form-group">
                        <label asp-for="Title" class="control-label">Tiêu đề</label>
                        <input asp-for="Title" class="form-control" />
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Content" class="control-label">Mô tả</label>
                        <textarea asp-for="Content" class="form-control" rows="5"></textarea>
                        <span asp-validation-for="Content" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="AreaId" class="control-label">Khu vực:</label>
                        <select asp-for="AreaId" class="form-control">
                            <option value=1>Hải Châu</option>
                            <option value=2>Thânh Khê</option>
                            <option value=3>Sơn Trà</option>
                            <option value=4>Liên Chiểu</option>
                            <option value=5>Cẩm Lệ</option>
                            <option value=6>Hòa Vang</option>
                            <option value=7>Ngũ Hành Sơn</option>
                        </select>
                    </div>
                    @*<div class="form-group">
                        <label asp-for="ImageURL" class="control-label">Link ảnh</label>
                        <input asp-for="ImageURL" class="" type="file" />
                        <span asp-validation-for="ImageURL" class="text-danger"></span>
                    </div>*@
                    <div class="form-group">

                        <input asp-for="ImageURL" value=@Model.ImageURL type="hidden" />

                    </div>
                    <div class="form-group">
                        <input type="submit" value="Lưu" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>

        <div>
            <a asp-action="ViewHistory">Quay lại</a>
        </div>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Posts/PostsByTheme.cshtml
@model IEnumerable<SemanticWeb.Models.Post>

@{
    ViewData["Title"] = "Post By Theme";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="row d-flex justify-content-center my-3">
        <form method="post" action="/Posts/SearchPosts" id="searchRDF-form" class="d-flex justify-content-between form-inline row">
            <input class="form-control col-8" type="text" placeholder="Tìm bài viết..." name="searchStringRDF" id="textboxRDF"/>
            <input type="submit" value="Tìm" class="btn btn-outline-warning font-weight-bolder col-3 float-right" />
        </form>
    </div>
    <div class="row" id="post-by-theme">
        <partial name="~/Views/Home/NewsFeedPartial.cshtml" />
    </div>

    @*<div class="card-columns">
            @foreach (var item in Model)
            {
                <div class="card border-info mb-3" data-toggle="modal" data-target="#myModal" data-id="@item.Id"
                     data-title="@item.Title" data-description="@item.Content" data-image="@item.ImageURL" data-date="@item.DatePosted">
                    <img class="card-img-top card-thumbnail" src="~/images/@item.ImageURL" alt="Card image cap">
                    <div class="card-body" style="height:80px;">
                        <h5 class="card-title d-flex align-items-center" style="height:50px;">@item.Title</h5>
                    </div>

                    <div class="card-footer d-flex justify-content-between">
                        <a class="btn btn-outline-info float-right" asp-action="Details" asp-route-id="@item.Id" asp-controller="Posts">Xem chi tiết</a>
                    </div>
                </div>
            }
        </div>


        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title text-center" id="myModalLabel" style="font-family: 'Pangolin', cursive;"></h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="card">
                            <img class="card-img-top" src="" alt="Card image cap" id="image-thumbnail">
                            <div class="card-body">
                                <p class="card-text" id="content"></p>
                            </div>
                        </div>
                        <div class="modal-footer d-flex justify-content-between">
                            <a class="btn btn-outline-info" id="detail-btn" href="">Xem chi tiết</a>
                            <p class="font-weight-bold">Ngày đăng: <span class="font-weight-light" id="date"></span> </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>*@


</div>

Views/Posts/Theme.cshtml
@{
    ViewData["Title"] = "Chủ đề du lịch";
}

<div class="row area-row-block">
    <a asp-action="PostsByTheme" asp-route-theme="tinhyeu" class="col-4 area-block area-block-tinhyeu">
        <h1>Tình Yêu</h1>
    </a>
    <a asp-action="PostsByTheme" asp-route-theme="maohiem" class="col-4 area-block area-block-maohiem">
        <h1>Mạo Hiểm</h1>
    </a>
    <a asp-action="PostsByTheme" asp-route-theme="nghiduong" class="col-4 area-block area-block-nghiduong">
        <h1>Nghỉ Dưỡng</h1>
    </a>
</div>
<div class="row area-row-block">
    <a asp-action="PostsByTheme" asp-route-theme="thethao" class="col-4 area-block area-block-thethao">
        <h1>Thể Thao</h1>
    </a>

    <a asp-action="PostsByTheme" asp-route-theme="hiendai" class="col-4 area-block area-block-hiendai">
        <h1>Hiện Đại</h1>
    </a>
    <a asp-action="PostsByTheme" asp-route-theme="giadinh" class="col-4 area-block area-block-giadinh">
        <h1>Gia Đình</h1>
    </a>
</div>
<div class="row area-row-block">
    <a asp-action="PostsByTheme" asp-route-theme="banbe" class="col-4 area-block area-block-banbe">
        <h1>Bạn Bè</h1>
    </a>

    <a asp-action="PostsByTheme" asp-route-theme="amthuc" class="col-4 area-block area-block-amthuc">
        <h1>Ẩm Thực</h1>
    </a>
    <a asp-action="PostsByTheme" asp-route-theme="thiennhien" class="col-4 area-block area-block-thiennhien">
        <h1>Thiên Nhiên</h1>
    </a>
</div>